name: Bug Report
description: Create a report to help us improve.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please share any of the following information that you think would be helpful:
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser were you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Browser
        - Other (please share in the description)
        - N/A
      default: 0
    validations:
      required: false
  - type: dropdown
    id: tcg
    attributes:
      label: TCG
      description: What TCG did you see the issue in?
      options:
        - Magic The Gathering
        - Pokemon
        - Other (please share in the description)
        - N/A
      default: 0
    validations:
      required: false
  - type: dropdown
    id: tcg-art-source
    attributes:
      label: Art Source
      description: What art source were you using when you saw the issue?
      options:
        - Scryfall
        - MPC Autofill
        - TCGdex
        - Other (please share in the description)
        - N/A
    validations:
      required: false
  - type: input
    id: deck-link
    attributes:
      label: Share link to the deck with an issue
      description: Provide click "Share Project" in the top right of the deck editor to share the deck (if you want to, it can help us recreate the issue).
      placeholder: https://proxxied.com/?share=...
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description of the issue
      description: A clear and concise description of what the bug is.
      placeholder: Please describe the issue here...
    validations:
      required: true
